<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>JToolsStub</AssemblyName>
    <LangVersion>default</LangVersion>
    <Deterministic>true</Deterministic>
    <RootNamespace>TierneyJohn.MiChangSheng.BepInExPlugin.JTools</RootNamespace>

    <GameDir>..\..\..\steamapps\common\觅长生\觅长生_Data\Managed</GameDir>
    <WorkShopDir>..\..\..\steamapps\workshop\content\1189490</WorkShopDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(WorkShopDir)\2824349934\BepInEx\core\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(WorkShopDir)\2824349934\BepInEx\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDir)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
